# Use the official Nginx image as the base
FROM nginx:alpine

# Copy the blue HTML file to the Nginx default directory
COPY index-latest.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
